variable "cluster_name" {
  description = "EKS Cluster"
  type        = string
}

variable "root_ca_arn" {
  description = "ARN of the root CA"
  type        = string
}

variable "root_domain_name" {
  description = "Domain name that this cluster is expecting to recieve traffic on, including subdomains. Ex: data-platform.sandbox.cloud-city, or dev.cloud-city"
  type        = string
}

variable "aws_internal_cluster_egress_rule_ids" {
  description = "Security group rule ID of the allow-all-outbound egress rule generated by AWS on the AWS-managed EKS egress security group, if any"
  type        = set(string)
}

variable "chart_ecr_image_account_id" {
  description = "AWS Account ID containing chart images to be used by this module. Should not ordinarily be changed from the default (the infra account)"
  type        = string
  default     = "381492150796"
}

variable "enable_argocd" {
  description = "Deploy ArgoCD?"
  type        = bool
  default     = true
}

variable "argocd_helm_chart_version" {
  description = "Version of the Helm chart for ArgoCD"
  type        = string
  default     = "8.1.2"
}

variable "external_secrets_helm_chart_version" {
  description = "Version of the Helm chart for External-Secrets"
  type        = string
  default     = "0.18.2"
}

variable "tags" {
  description = "Tags to apply to the resources"
  type        = map(string)
  default     = {}
}
